#!/usr/bin/env bash
# Fast restore: loads pre-computed passages + subscription_databases from SQL dump.
# Skips the 3-hour embedding step entirely.
#
# Usage: bash data/restore_all.sh
# Run from the project root after: docker compose up -d postgres
# Requires: data/passages_full.sql.gz (generated by data/dump_all.sh)

set -e
COMPOSE="docker compose"
DB="gju_library"
USER="gju"
DUMP="data/passages_full.sql.gz"

if [ ! -f "$DUMP" ]; then
  echo "ERROR: $DUMP not found. Run bash data/dump_all.sh after a successful ingest first."
  exit 1
fi

SIZE=$(du -sh "$DUMP" | cut -f1)
echo "==> Restoring from $DUMP ($SIZE)..."

echo "==> Truncating existing data..."
$COMPOSE exec -T postgres psql -U $USER -d $DB -c \
  "TRUNCATE passages RESTART IDENTITY; TRUNCATE subscription_databases CASCADE;"

echo "==> Loading data (this takes ~30-60 seconds)..."
gunzip -c "$DUMP" | $COMPOSE exec -T postgres psql -U $USER -d $DB

echo "==> Rebuilding search indexes..."
$COMPOSE exec -T postgres psql -U $USER -d $DB -c "
  UPDATE passages SET search_vector = to_tsvector('english', coalesce(title,'') || ' ' || coalesce(body,''))
  WHERE search_vector IS NULL;
"

echo "==> Row counts:"
$COMPOSE exec -T postgres psql -U $USER -d $DB -c \
  "SELECT source, lang, count(*) FROM passages GROUP BY source, lang ORDER BY source, lang;"

echo ""
echo "==> Done. No re-embedding needed."
